[package]
name = "zinc"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = { version = "0.20.0", features = ["crossterm-backend"], default-features = false}
cursive-tabs = "0.7.0"
fs_extra = "1.3.0"
